language: python
sudo: required
dist: xenial
branches:
  only:
    master
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  # add a latex install for the matplotlib testing
  #- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
  # try a lighter weight texlive distribution, e.g. just texlive and texlive-latex-extra
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive texlive-latex-extra cm-super dvipng latexmk
services:  # see https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb
  - xvfb
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  # install additionally allowed packages
  - pip install matplotlib ads
  # install packages for documentation building
  - pip install sphinx sphinx-rtd-theme recommonmark
  # install packages for testing
  - pip install --upgrade pytest>=3.6.3
  - pip install pytest-cov pytest-socket
  - pip install codecov
  # build psrqpy
  - pip install -e .
script:
  # run the test script
  - pytest --cov=psrqpy
  # try building documentation
  - cd docs
  - mkdir source/_static
  - make html
  # return to base directory
  - cd .. 
after_success:
  - codecov
